.MODEL SMALL
.STACK 100H

.DATA
    ARRAY        DW 7 DUP(?)         
    TEMPORARY    DB ?                
    PROMPT       DB "Enter a number: $"
    PROMPT_2     DB "Enter number to search: $"
    FOUND_MSG    DB 0DH,0AH,"NUMBER FOUND!$"
    NOT_FOUND    DB 0DH,0AH,"NUMBER NOT FOUND!$"
    SUM_MSG      DB 0DH,0AH,"SUM IS: $"
    AVG_MSG      DB 0DH,0AH,"AVERAGE IS: $"
    MIN_MSG      DB 0DH,0AH,"MINIMUM VALUE IS: $"
    MAX_MSG      DB 0DH,0AH,"MAXIMUM VALUE IS: $"
    MENU_MAIN    DB 0DH,0AH,"1. ARRAY OPERATIONS",0DH,0AH,"2. EXIT$"
    MENU_OPS     DB 0DH,0AH,"1. DISPLAY ARRAY",0DH,0AH,"2. SEARCH NUMBER",0DH,0AH,"3. SUM",0DH,0AH,"4. AVERAGE",0DH,0AH,"5. MINIMUM",0DH,0AH,"6. MAXIMUM",0DH,0AH,"7. BACK$"
    ERROR_MSG    DB 0DH,0AH,"INVALID INPUT! TRY AGAIN$"
    NEWLINE      DB 0DH,0AH,"$"
    TOTAL        DW ?
    CHOICE       DB ?

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    ; ===== INPUT ARRAY =====
    MOV CX, 7
    MOV SI, OFFSET ARRAY
INPUT_ARRAY:
    MOV DX, OFFSET PROMPT
    CALL PRINT_STRING
    CALL DECIMAL_INPUT
    MOV [SI], AX
    ADD SI, 2
    MOV DX, OFFSET NEWLINE
    CALL PRINT_STRING
    LOOP INPUT_ARRAY


MAIN_MENU:
    MOV DX, OFFSET MENU_MAIN
    CALL PRINT_STRING
    MOV DX, OFFSET NEWLINE
    CALL PRINT_STRING 
    CALL CHARACTER_INPUT
    CMP AL, '1'
    JE ARRAY_MENU
    CMP AL, '2'
    JE QUIT
    JMP INVALID

ARRAY_MENU:
    MOV DX, OFFSET NEWLINE
    CALL PRINT_STRING
    MOV DX, OFFSET MENU_OPS
    CALL PRINT_STRING
ARRAY_CHOICE:
    MOV DX, OFFSET NEWLINE
    CALL PRINT_STRING
    CALL CHARACTER_INPUT
    CMP AL, '1'
    JE DISPLAY_ARRAY
    CMP AL, '2'
    JE SEARCH_VALUE
    CMP AL, '3'
    JE CALC_SUM
    CMP AL, '4'
    JE CALC_AVG
    CMP AL, '5'
    JE FIND_MIN
    CMP AL, '6'
    JE FIND_MAX
    CMP AL, '7'
    JMP MAIN_MENU
    JMP INVALID

DISPLAY_ARRAY:
    MOV CX, 7
    MOV SI, OFFSET ARRAY
DISPLAY_LOOP:
    MOV AX, [SI]
    CALL DECIMAL_OUTPUT
    MOV DL, ' '
    CALL CHARACTER_OUTPUT
    ADD SI, 2
    LOOP DISPLAY_LOOP
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU

SEARCH_VALUE:
    MOV DX, OFFSET PROMPT_2
    CALL PRINT_STRING
    CALL DECIMAL_INPUT
    MOV BX, AX
    MOV CX, 7
    MOV SI, OFFSET ARRAY
SEARCH_LOOP:
    MOV AX, [SI]
    CMP AX, BX
    JE VALUE_FOUND
    ADD SI, 2
    LOOP SEARCH_LOOP
    MOV DX, OFFSET NOT_FOUND
    CALL PRINT_STRING
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU
VALUE_FOUND:
    MOV DX, OFFSET FOUND_MSG
    CALL PRINT_STRING
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU

CALC_SUM:
    MOV CX, 7
    MOV SI, OFFSET ARRAY
    MOV AX, 0
SUM_LOOP:
    ADD AX, [SI]
    ADD SI, 2
    LOOP SUM_LOOP
    MOV TOTAL, AX
    MOV DX, OFFSET SUM_MSG
    CALL PRINT_STRING
    MOV AX, TOTAL
    CALL DECIMAL_OUTPUT
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU

CALC_AVG:
    MOV AX, TOTAL
    MOV DX, 0
    MOV CX, 7
    DIV CX
    MOV DX, OFFSET AVG_MSG
    CALL PRINT_STRING
    CALL DECIMAL_OUTPUT
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU

FIND_MIN:
    MOV SI, OFFSET ARRAY
    MOV BX, [SI]
    MOV CX, 6
    ADD SI, 2
MIN_LOOP:
    CMP BX, [SI]
    JLE NO_MIN_SWAP
    MOV BX, [SI]
NO_MIN_SWAP:
    ADD SI, 2
    LOOP MIN_LOOP
    MOV AX, BX
    MOV DX, OFFSET MIN_MSG
    CALL PRINT_STRING
    CALL DECIMAL_OUTPUT
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU

FIND_MAX:
    MOV SI, OFFSET ARRAY
    MOV BX, [SI]
    MOV CX, 6
    ADD SI, 2
MAX_LOOP:
    CMP BX, [SI]
    JGE NO_MAX_SWAP
    MOV BX, [SI]
NO_MAX_SWAP:
    ADD SI, 2
    LOOP MAX_LOOP
    MOV AX, BX
    MOV DX, OFFSET MAX_MSG
    CALL PRINT_STRING
    CALL DECIMAL_OUTPUT
    CALL NEWLINE_PRINT
    JMP ARRAY_MENU

INVALID:
    MOV DX, OFFSET ERROR_MSG
    CALL PRINT_STRING
    CALL NEWLINE_PRINT
    JMP MAIN_MENU

QUIT:
    MOV AH, 4CH
    INT 21H
MAIN ENDP

DECIMAL_INPUT PROC
    PUSH CX
    MOV BX, 0
    MOV CX, 10
READ_CHAR:
    CALL CHARACTER_INPUT
    MOV AL, TEMPORARY
    CMP AL, 13
    JE FINISH_INPUT
    CMP AL, '0'
    JB READ_CHAR
    CMP AL, '9'
    JA READ_CHAR
    SUB AL, '0'
    MOV AH, 0
    PUSH AX
    MOV AX, BX
    MUL CX
    POP BX
    ADD BX, AX
    JMP READ_CHAR
FINISH_INPUT:
    MOV AX, BX
    POP CX
    RET
DECIMAL_INPUT ENDP

DECIMAL_OUTPUT PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    MOV BX, 10
    MOV CX, 0
DIV_LOOP:
    MOV DX, 0
    DIV BX
    PUSH DX
    INC CX
    CMP AX, 0
    JNZ DIV_LOOP
OUT_LOOP:
    POP DX
    ADD DL, '0'
    CALL CHARACTER_OUTPUT
    LOOP OUT_LOOP
    POP DX
    POP CX
    POP BX
    POP AX
    RET
DECIMAL_OUTPUT ENDP

CHARACTER_INPUT PROC
    MOV AH, 1
    INT 21H
    MOV TEMPORARY, AL
    RET
CHARACTER_INPUT ENDP

CHARACTER_OUTPUT PROC
    MOV AH, 2
    INT 21H
    RET
CHARACTER_OUTPUT ENDP

PRINT_STRING PROC
    MOV AH, 9
    INT 21H
    RET
PRINT_STRING ENDP

NEWLINE_PRINT PROC
    MOV DX, OFFSET NEWLINE
    CALL PRINT_STRING
    RET
NEWLINE_PRINT ENDP

END MAIN
