                                         .MODEL SMALL
.STACK 100H

.DATA
    MY_TEXT        DB ' I AM A PROUD PAKISTANII$', 0
    SHOW_VOWEL     DB 'VOWELS: $'
    SHOW_CONSONANT DB 13, 10, 'CONSONANTS: $'
    COUNT_VOWELS   DW 0
    COUNT_CONS     DW 0

.CODE
BEGIN:
    MOV AX, @DATA
    MOV DS, AX

    MOV SI, OFFSET MY_TEXT

CHECK_LOOP:
    MOV AL, [SI]
    CMP AL, '$'
    JE DISPLAY_RESULTS

    CMP AL, 'A'
    JL SKIP_THIS
    CMP AL, 'Z'
    JLE TO_LOWER
    CMP AL, 'a'
    JL SKIP_THIS
    CMP AL, 'z'
    JG SKIP_THIS

    JMP VOWEL_CHECK

TO_LOWER:
    ADD AL, 32

VOWEL_CHECK:
    CMP AL, 'a'
    JE FOUND_VOWEL
    CMP AL, 'e'
    JE FOUND_VOWEL
    CMP AL, 'i'
    JE FOUND_VOWEL
    CMP AL, 'o'
    JE FOUND_VOWEL
    CMP AL, 'u'
    JE FOUND_VOWEL

    INC COUNT_CONS
    JMP MOVE_NEXT

FOUND_VOWEL:
    INC COUNT_VOWELS
    JMP MOVE_NEXT

SKIP_THIS:
    JMP MOVE_NEXT

MOVE_NEXT:
    INC SI
    JMP CHECK_LOOP

DISPLAY_RESULTS:
    MOV DX, OFFSET SHOW_VOWEL
    MOV AH,09
    INT 21H

    MOV AX, COUNT_VOWELS
    CALL DECIMAL_OUTPUT

    MOV DX, OFFSET SHOW_CONSONANT
    MOV AH,09 
    INT 21H

    MOV AX, COUNT_CONS
    CALL DECIMAL_OUTPUT

    MOV AH, 4CH
    INT 21H

DECIMAL_OUTPUT PROC
    MOV BX,10
    MOV CX,0
        OUTDEC_1:
            MOV DX,0
            DIV BX
            PUSH DX
            INC CX
            CMP AX,0
            JNZ OUTDEC_1
            
            DISPLAY_DIGITS:
                POP DX
                ADD DX,'0'
                CALL CHARACTER_OUTPUT
                LOOP DISPLAY_DIGITS
     
D     RET
DECIMAL_OUTPUT ENDP     
                
    

CHARACTER_OUTPUT PROC
    MOV AH,2
    INT 21H
    
    RET
    
CHARACTER_OUTPUT ENDP    